import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import { Toaster } from "@/components/ui/toaster";
import getCurrentUser from "./actions/getCurrenUser";

const inter = Roboto({ subsets: ["latin"], weight: ["400", "500", "900"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const currentUser = await getCurrentUser();
  console.log(currentUser);
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Navbar user={currentUser} /> */}
        <Toaster />
        {children}
      </body>
    </html>
  );
}
